create table tb_product (price float(53) not null, id bigserial not null, description TEXT, name varchar(255), primary key (id));
INSERT INTO tb_product (name, description, price) VALUES ('Bola de Futebol', 'Bola de Futebol Nunes Sports: durável, design clássico, toques precisos', 119.90);
INSERT INTO tb_product (name, description, price) VALUES ('Chuteira Nike Mercurial', 'Chuteira profissional para jogadores de futebol', 229.90);
INSERT INTO tb_product (name, description, price) VALUES ('Camisa Oficial do Time', 'Camisa de jogo oficial do time Nunes Sports', 79.99);
INSERT INTO tb_product (name, description, price) VALUES ('Rede de Futebol', 'Rede resistente para treinos e partidas', 49.90);
INSERT INTO tb_product (name, description, price) VALUES ('Tênis de Corrida Asics Gel', 'Tênis de alta performance para corridas', 189.99);
INSERT INTO tb_product (name, description, price) VALUES ('Shorts Térmico para Corrida', 'Shorts confortável para corridas longas', 59.90);
INSERT INTO tb_product (name, description, price) VALUES ('Garrafa de Hidratação Esportiva', 'Garrafa com design ergonômico para atletas', 39.90);
INSERT INTO tb_product (name, description, price) VALUES ('Bola de Basquete Spalding', 'Bola oficial de basquete para treinos e competições', 79.90);
INSERT INTO tb_product (name, description, price) VALUES ('Tênis de Basquete Adidas', 'Tênis de alta aderência e suporte para jogadores de basquete', 119.99);
INSERT INTO tb_product (name, description, price) VALUES ('Aro de Basquete Resistente', 'Aro de aço para prática intensa de basquete', 79.90);
INSERT INTO tb_product (name, description, price) VALUES ('Luvas de Goleiro Profissional', 'Luvas com grip superior para goleiros', 149.90);
INSERT INTO tb_product (name, description, price) VALUES ('Caneleira de Proteção Nike', 'Caneleira leve e resistente para proteção durante os jogos', 69.90);
INSERT INTO tb_product (name, description, price) VALUES ('Meião Esportivo', 'Meião confortável para prática esportiva', 19.90);
INSERT INTO tb_product (name, description, price) VALUES ('Raquete de Tênis Wilson', 'Raquete de alta qualidade para jogadores exigentes', 159.90);
INSERT INTO tb_product (name, description, price) VALUES ('Bola de Vôlei Mikasa', 'Bola oficial para treinos e competições de vôlei', 89.90);
INSERT INTO tb_product (name, description, price) VALUES ('Tênis de Squash Head', 'Calçado projetado para movimentos rápidos em quadra', 129.90);
INSERT INTO tb_product (name, description, price) VALUES ('Mochila Esportiva Adidas', 'Mochila resistente e espaçosa para atletas', 79.90);
INSERT INTO tb_product (name, description, price) VALUES ('Boné de Corrida', 'Boné leve e respirável para corridas ao ar livre', 29.90);
INSERT INTO tb_product (name, description, price) VALUES ('Corda de Pular Profissional', 'Corda ajustável para treinos intensos de cardio', 14.90);
INSERT INTO tb_product (name, description, price) VALUES ('Joelheira de Suporte', 'Joelheira confortável para suporte durante atividades físicas', 34.90);
INSERT INTO tb_product (name, description, price) VALUES ('Skate Completo', 'Skate para iniciantes com design moderno', 99.90);
INSERT INTO tb_product (name, description, price) VALUES ('Relógio Esportivo Garmin', 'Relógio com recursos avançados para monitoramento de atividades', 279.90);
INSERT INTO tb_product (name, description, price) VALUES ('Máscara de Treino', 'Máscara para simular treinamento em altas altitudes', 44.90);
INSERT INTO tb_product (name, description, price) VALUES ('Elásticos de Resistência', 'Conjunto de elásticos para treinos de resistência', 29.90);
INSERT INTO tb_product (name, description, price) VALUES ('Squeeze de Alumínio', 'Squeeze durável para manter-se hidratado durante os exercícios', 19.90);
create table tb_product (price float(53) not null, id bigserial not null, description TEXT, name varchar(255), primary key (id));
INSERT INTO tb_product (name, description, price) VALUES ('Bola de Futebol', 'Bola de Futebol Nunes Sports: durável, design clássico, toques precisos', 119.90);
INSERT INTO tb_product (name, description, price) VALUES ('Chuteira Nike Mercurial', 'Chuteira profissional para jogadores de futebol', 229.90);
INSERT INTO tb_product (name, description, price) VALUES ('Camisa Oficial do Time', 'Camisa de jogo oficial do time Nunes Sports', 79.99);
INSERT INTO tb_product (name, description, price) VALUES ('Rede de Futebol', 'Rede resistente para treinos e partidas', 49.90);
INSERT INTO tb_product (name, description, price) VALUES ('Tênis de Corrida Asics Gel', 'Tênis de alta performance para corridas', 189.99);
INSERT INTO tb_product (name, description, price) VALUES ('Shorts Térmico para Corrida', 'Shorts confortável para corridas longas', 59.90);
INSERT INTO tb_product (name, description, price) VALUES ('Garrafa de Hidratação Esportiva', 'Garrafa com design ergonômico para atletas', 39.90);
INSERT INTO tb_product (name, description, price) VALUES ('Bola de Basquete Spalding', 'Bola oficial de basquete para treinos e competições', 79.90);
INSERT INTO tb_product (name, description, price) VALUES ('Tênis de Basquete Adidas', 'Tênis de alta aderência e suporte para jogadores de basquete', 119.99);
INSERT INTO tb_product (name, description, price) VALUES ('Aro de Basquete Resistente', 'Aro de aço para prática intensa de basquete', 79.90);
INSERT INTO tb_product (name, description, price) VALUES ('Luvas de Goleiro Profissional', 'Luvas com grip superior para goleiros', 149.90);
INSERT INTO tb_product (name, description, price) VALUES ('Caneleira de Proteção Nike', 'Caneleira leve e resistente para proteção durante os jogos', 69.90);
INSERT INTO tb_product (name, description, price) VALUES ('Meião Esportivo', 'Meião confortável para prática esportiva', 19.90);
INSERT INTO tb_product (name, description, price) VALUES ('Raquete de Tênis Wilson', 'Raquete de alta qualidade para jogadores exigentes', 159.90);
INSERT INTO tb_product (name, description, price) VALUES ('Bola de Vôlei Mikasa', 'Bola oficial para treinos e competições de vôlei', 89.90);
INSERT INTO tb_product (name, description, price) VALUES ('Tênis de Squash Head', 'Calçado projetado para movimentos rápidos em quadra', 129.90);
INSERT INTO tb_product (name, description, price) VALUES ('Mochila Esportiva Adidas', 'Mochila resistente e espaçosa para atletas', 79.90);
INSERT INTO tb_product (name, description, price) VALUES ('Boné de Corrida', 'Boné leve e respirável para corridas ao ar livre', 29.90);
INSERT INTO tb_product (name, description, price) VALUES ('Corda de Pular Profissional', 'Corda ajustável para treinos intensos de cardio', 14.90);
INSERT INTO tb_product (name, description, price) VALUES ('Joelheira de Suporte', 'Joelheira confortável para suporte durante atividades físicas', 34.90);
INSERT INTO tb_product (name, description, price) VALUES ('Skate Completo', 'Skate para iniciantes com design moderno', 99.90);
INSERT INTO tb_product (name, description, price) VALUES ('Relógio Esportivo Garmin', 'Relógio com recursos avançados para monitoramento de atividades', 279.90);
INSERT INTO tb_product (name, description, price) VALUES ('Máscara de Treino', 'Máscara para simular treinamento em altas altitudes', 44.90);
INSERT INTO tb_product (name, description, price) VALUES ('Elásticos de Resistência', 'Conjunto de elásticos para treinos de resistência', 29.90);
INSERT INTO tb_product (name, description, price) VALUES ('Squeeze de Alumínio', 'Squeeze durável para manter-se hidratado durante os exercícios', 19.90);
create table tb_product (price float(53) not null, id bigserial not null, description TEXT, name varchar(255), primary key (id));
INSERT INTO tb_product (name, description, price) VALUES ('Bola de Futebol', 'Bola de Futebol Nunes Sports: durável, design clássico, toques precisos', 119.90);
INSERT INTO tb_product (name, description, price) VALUES ('Chuteira Nike Mercurial', 'Chuteira profissional para jogadores de futebol', 229.90);
INSERT INTO tb_product (name, description, price) VALUES ('Camisa Oficial do Time', 'Camisa de jogo oficial do time Nunes Sports', 79.99);
INSERT INTO tb_product (name, description, price) VALUES ('Rede de Futebol', 'Rede resistente para treinos e partidas', 49.90);
INSERT INTO tb_product (name, description, price) VALUES ('Tênis de Corrida Asics Gel', 'Tênis de alta performance para corridas', 189.99);
INSERT INTO tb_product (name, description, price) VALUES ('Shorts Térmico para Corrida', 'Shorts confortável para corridas longas', 59.90);
INSERT INTO tb_product (name, description, price) VALUES ('Garrafa de Hidratação Esportiva', 'Garrafa com design ergonômico para atletas', 39.90);
INSERT INTO tb_product (name, description, price) VALUES ('Bola de Basquete Spalding', 'Bola oficial de basquete para treinos e competições', 79.90);
INSERT INTO tb_product (name, description, price) VALUES ('Tênis de Basquete Adidas', 'Tênis de alta aderência e suporte para jogadores de basquete', 119.99);
INSERT INTO tb_product (name, description, price) VALUES ('Aro de Basquete Resistente', 'Aro de aço para prática intensa de basquete', 79.90);
INSERT INTO tb_product (name, description, price) VALUES ('Luvas de Goleiro Profissional', 'Luvas com grip superior para goleiros', 149.90);
INSERT INTO tb_product (name, description, price) VALUES ('Caneleira de Proteção Nike', 'Caneleira leve e resistente para proteção durante os jogos', 69.90);
INSERT INTO tb_product (name, description, price) VALUES ('Meião Esportivo', 'Meião confortável para prática esportiva', 19.90);
INSERT INTO tb_product (name, description, price) VALUES ('Raquete de Tênis Wilson', 'Raquete de alta qualidade para jogadores exigentes', 159.90);
INSERT INTO tb_product (name, description, price) VALUES ('Bola de Vôlei Mikasa', 'Bola oficial para treinos e competições de vôlei', 89.90);
INSERT INTO tb_product (name, description, price) VALUES ('Tênis de Squash Head', 'Calçado projetado para movimentos rápidos em quadra', 129.90);
INSERT INTO tb_product (name, description, price) VALUES ('Mochila Esportiva Adidas', 'Mochila resistente e espaçosa para atletas', 79.90);
INSERT INTO tb_product (name, description, price) VALUES ('Boné de Corrida', 'Boné leve e respirável para corridas ao ar livre', 29.90);
INSERT INTO tb_product (name, description, price) VALUES ('Corda de Pular Profissional', 'Corda ajustável para treinos intensos de cardio', 14.90);
INSERT INTO tb_product (name, description, price) VALUES ('Joelheira de Suporte', 'Joelheira confortável para suporte durante atividades físicas', 34.90);
INSERT INTO tb_product (name, description, price) VALUES ('Skate Completo', 'Skate para iniciantes com design moderno', 99.90);
INSERT INTO tb_product (name, description, price) VALUES ('Relógio Esportivo Garmin', 'Relógio com recursos avançados para monitoramento de atividades', 279.90);
INSERT INTO tb_product (name, description, price) VALUES ('Máscara de Treino', 'Máscara para simular treinamento em altas altitudes', 44.90);
INSERT INTO tb_product (name, description, price) VALUES ('Elásticos de Resistência', 'Conjunto de elásticos para treinos de resistência', 29.90);
INSERT INTO tb_product (name, description, price) VALUES ('Squeeze de Alumínio', 'Squeeze durável para manter-se hidratado durante os exercícios', 19.90);
create table tb_product (price float(53) not null, id bigserial not null, description TEXT, name varchar(255), primary key (id));
INSERT INTO tb_product (name, description, price) VALUES ('Bola de Futebol', 'Bola de Futebol Nunes Sports: durável, design clássico, toques precisos', 119.90);
INSERT INTO tb_product (name, description, price) VALUES ('Chuteira Nike Mercurial', 'Chuteira profissional para jogadores de futebol', 229.90);
INSERT INTO tb_product (name, description, price) VALUES ('Camisa Oficial do Time', 'Camisa de jogo oficial do time Nunes Sports', 79.99);
INSERT INTO tb_product (name, description, price) VALUES ('Rede de Futebol', 'Rede resistente para treinos e partidas', 49.90);
INSERT INTO tb_product (name, description, price) VALUES ('Tênis de Corrida Asics Gel', 'Tênis de alta performance para corridas', 189.99);
INSERT INTO tb_product (name, description, price) VALUES ('Shorts Térmico para Corrida', 'Shorts confortável para corridas longas', 59.90);
INSERT INTO tb_product (name, description, price) VALUES ('Garrafa de Hidratação Esportiva', 'Garrafa com design ergonômico para atletas', 39.90);
INSERT INTO tb_product (name, description, price) VALUES ('Bola de Basquete Spalding', 'Bola oficial de basquete para treinos e competições', 79.90);
INSERT INTO tb_product (name, description, price) VALUES ('Tênis de Basquete Adidas', 'Tênis de alta aderência e suporte para jogadores de basquete', 119.99);
INSERT INTO tb_product (name, description, price) VALUES ('Aro de Basquete Resistente', 'Aro de aço para prática intensa de basquete', 79.90);
INSERT INTO tb_product (name, description, price) VALUES ('Luvas de Goleiro Profissional', 'Luvas com grip superior para goleiros', 149.90);
INSERT INTO tb_product (name, description, price) VALUES ('Caneleira de Proteção Nike', 'Caneleira leve e resistente para proteção durante os jogos', 69.90);
INSERT INTO tb_product (name, description, price) VALUES ('Meião Esportivo', 'Meião confortável para prática esportiva', 19.90);
INSERT INTO tb_product (name, description, price) VALUES ('Raquete de Tênis Wilson', 'Raquete de alta qualidade para jogadores exigentes', 159.90);
INSERT INTO tb_product (name, description, price) VALUES ('Bola de Vôlei Mikasa', 'Bola oficial para treinos e competições de vôlei', 89.90);
INSERT INTO tb_product (name, description, price) VALUES ('Tênis de Squash Head', 'Calçado projetado para movimentos rápidos em quadra', 129.90);
INSERT INTO tb_product (name, description, price) VALUES ('Mochila Esportiva Adidas', 'Mochila resistente e espaçosa para atletas', 79.90);
INSERT INTO tb_product (name, description, price) VALUES ('Boné de Corrida', 'Boné leve e respirável para corridas ao ar livre', 29.90);
INSERT INTO tb_product (name, description, price) VALUES ('Corda de Pular Profissional', 'Corda ajustável para treinos intensos de cardio', 14.90);
INSERT INTO tb_product (name, description, price) VALUES ('Joelheira de Suporte', 'Joelheira confortável para suporte durante atividades físicas', 34.90);
INSERT INTO tb_product (name, description, price) VALUES ('Skate Completo', 'Skate para iniciantes com design moderno', 99.90);
INSERT INTO tb_product (name, description, price) VALUES ('Relógio Esportivo Garmin', 'Relógio com recursos avançados para monitoramento de atividades', 279.90);
INSERT INTO tb_product (name, description, price) VALUES ('Máscara de Treino', 'Máscara para simular treinamento em altas altitudes', 44.90);
INSERT INTO tb_product (name, description, price) VALUES ('Elásticos de Resistência', 'Conjunto de elásticos para treinos de resistência', 29.90);
INSERT INTO tb_product (name, description, price) VALUES ('Squeeze de Alumínio', 'Squeeze durável para manter-se hidratado durante os exercícios', 19.90);
create table tb_product (price float(53) not null, id bigserial not null, description TEXT, name varchar(255), primary key (id));
INSERT INTO tb_product (name, description, price) VALUES ('Bola de Futebol', 'Bola de Futebol Nunes Sports: durável, design clássico, toques precisos', 119.90);
INSERT INTO tb_product (name, description, price) VALUES ('Chuteira Nike Mercurial', 'Chuteira profissional para jogadores de futebol', 229.90);
INSERT INTO tb_product (name, description, price) VALUES ('Camisa Oficial do Time', 'Camisa de jogo oficial do time Nunes Sports', 79.99);
INSERT INTO tb_product (name, description, price) VALUES ('Rede de Futebol', 'Rede resistente para treinos e partidas', 49.90);
INSERT INTO tb_product (name, description, price) VALUES ('Tênis de Corrida Asics Gel', 'Tênis de alta performance para corridas', 189.99);
INSERT INTO tb_product (name, description, price) VALUES ('Shorts Térmico para Corrida', 'Shorts confortável para corridas longas', 59.90);
INSERT INTO tb_product (name, description, price) VALUES ('Garrafa de Hidratação Esportiva', 'Garrafa com design ergonômico para atletas', 39.90);
INSERT INTO tb_product (name, description, price) VALUES ('Bola de Basquete Spalding', 'Bola oficial de basquete para treinos e competições', 79.90);
INSERT INTO tb_product (name, description, price) VALUES ('Tênis de Basquete Adidas', 'Tênis de alta aderência e suporte para jogadores de basquete', 119.99);
INSERT INTO tb_product (name, description, price) VALUES ('Aro de Basquete Resistente', 'Aro de aço para prática intensa de basquete', 79.90);
INSERT INTO tb_product (name, description, price) VALUES ('Luvas de Goleiro Profissional', 'Luvas com grip superior para goleiros', 149.90);
INSERT INTO tb_product (name, description, price) VALUES ('Caneleira de Proteção Nike', 'Caneleira leve e resistente para proteção durante os jogos', 69.90);
INSERT INTO tb_product (name, description, price) VALUES ('Meião Esportivo', 'Meião confortável para prática esportiva', 19.90);
INSERT INTO tb_product (name, description, price) VALUES ('Raquete de Tênis Wilson', 'Raquete de alta qualidade para jogadores exigentes', 159.90);
INSERT INTO tb_product (name, description, price) VALUES ('Bola de Vôlei Mikasa', 'Bola oficial para treinos e competições de vôlei', 89.90);
INSERT INTO tb_product (name, description, price) VALUES ('Tênis de Squash Head', 'Calçado projetado para movimentos rápidos em quadra', 129.90);
INSERT INTO tb_product (name, description, price) VALUES ('Mochila Esportiva Adidas', 'Mochila resistente e espaçosa para atletas', 79.90);
INSERT INTO tb_product (name, description, price) VALUES ('Boné de Corrida', 'Boné leve e respirável para corridas ao ar livre', 29.90);
INSERT INTO tb_product (name, description, price) VALUES ('Corda de Pular Profissional', 'Corda ajustável para treinos intensos de cardio', 14.90);
INSERT INTO tb_product (name, description, price) VALUES ('Joelheira de Suporte', 'Joelheira confortável para suporte durante atividades físicas', 34.90);
INSERT INTO tb_product (name, description, price) VALUES ('Skate Completo', 'Skate para iniciantes com design moderno', 99.90);
INSERT INTO tb_product (name, description, price) VALUES ('Relógio Esportivo Garmin', 'Relógio com recursos avançados para monitoramento de atividades', 279.90);
INSERT INTO tb_product (name, description, price) VALUES ('Máscara de Treino', 'Máscara para simular treinamento em altas altitudes', 44.90);
INSERT INTO tb_product (name, description, price) VALUES ('Elásticos de Resistência', 'Conjunto de elásticos para treinos de resistência', 29.90);
INSERT INTO tb_product (name, description, price) VALUES ('Squeeze de Alumínio', 'Squeeze durável para manter-se hidratado durante os exercícios', 19.90);
create table tb_product (price float(53) not null, id bigserial not null, description TEXT, name varchar(255), primary key (id));
INSERT INTO tb_product (name, description, price) VALUES ('Bola de Futebol', 'Bola de Futebol Nunes Sports: durável, design clássico, toques precisos', 119.90);
INSERT INTO tb_product (name, description, price) VALUES ('Chuteira Nike Mercurial', 'Chuteira profissional para jogadores de futebol', 229.90);
INSERT INTO tb_product (name, description, price) VALUES ('Camisa Oficial do Time', 'Camisa de jogo oficial do time Nunes Sports', 79.99);
INSERT INTO tb_product (name, description, price) VALUES ('Rede de Futebol', 'Rede resistente para treinos e partidas', 49.90);
INSERT INTO tb_product (name, description, price) VALUES ('Tênis de Corrida Asics Gel', 'Tênis de alta performance para corridas', 189.99);
INSERT INTO tb_product (name, description, price) VALUES ('Shorts Térmico para Corrida', 'Shorts confortável para corridas longas', 59.90);
INSERT INTO tb_product (name, description, price) VALUES ('Garrafa de Hidratação Esportiva', 'Garrafa com design ergonômico para atletas', 39.90);
INSERT INTO tb_product (name, description, price) VALUES ('Bola de Basquete Spalding', 'Bola oficial de basquete para treinos e competições', 79.90);
INSERT INTO tb_product (name, description, price) VALUES ('Tênis de Basquete Adidas', 'Tênis de alta aderência e suporte para jogadores de basquete', 119.99);
INSERT INTO tb_product (name, description, price) VALUES ('Aro de Basquete Resistente', 'Aro de aço para prática intensa de basquete', 79.90);
INSERT INTO tb_product (name, description, price) VALUES ('Luvas de Goleiro Profissional', 'Luvas com grip superior para goleiros', 149.90);
INSERT INTO tb_product (name, description, price) VALUES ('Caneleira de Proteção Nike', 'Caneleira leve e resistente para proteção durante os jogos', 69.90);
INSERT INTO tb_product (name, description, price) VALUES ('Meião Esportivo', 'Meião confortável para prática esportiva', 19.90);
INSERT INTO tb_product (name, description, price) VALUES ('Raquete de Tênis Wilson', 'Raquete de alta qualidade para jogadores exigentes', 159.90);
INSERT INTO tb_product (name, description, price) VALUES ('Bola de Vôlei Mikasa', 'Bola oficial para treinos e competições de vôlei', 89.90);
INSERT INTO tb_product (name, description, price) VALUES ('Tênis de Squash Head', 'Calçado projetado para movimentos rápidos em quadra', 129.90);
INSERT INTO tb_product (name, description, price) VALUES ('Mochila Esportiva Adidas', 'Mochila resistente e espaçosa para atletas', 79.90);
INSERT INTO tb_product (name, description, price) VALUES ('Boné de Corrida', 'Boné leve e respirável para corridas ao ar livre', 29.90);
INSERT INTO tb_product (name, description, price) VALUES ('Corda de Pular Profissional', 'Corda ajustável para treinos intensos de cardio', 14.90);
INSERT INTO tb_product (name, description, price) VALUES ('Joelheira de Suporte', 'Joelheira confortável para suporte durante atividades físicas', 34.90);
INSERT INTO tb_product (name, description, price) VALUES ('Skate Completo', 'Skate para iniciantes com design moderno', 99.90);
INSERT INTO tb_product (name, description, price) VALUES ('Relógio Esportivo Garmin', 'Relógio com recursos avançados para monitoramento de atividades', 279.90);
INSERT INTO tb_product (name, description, price) VALUES ('Máscara de Treino', 'Máscara para simular treinamento em altas altitudes', 44.90);
INSERT INTO tb_product (name, description, price) VALUES ('Elásticos de Resistência', 'Conjunto de elásticos para treinos de resistência', 29.90);
INSERT INTO tb_product (name, description, price) VALUES ('Squeeze de Alumínio', 'Squeeze durável para manter-se hidratado durante os exercícios', 19.90);
create table tb_product (price float(53) not null, id bigserial not null, description TEXT, name varchar(255), primary key (id));
INSERT INTO tb_product (name, description, price) VALUES ('Bola de Futebol', 'Bola de Futebol Nunes Sports: durável, design clássico, toques precisos', 119.90);
INSERT INTO tb_product (name, description, price) VALUES ('Chuteira Nike Mercurial', 'Chuteira profissional para jogadores de futebol', 229.90);
INSERT INTO tb_product (name, description, price) VALUES ('Camisa Oficial do Time', 'Camisa de jogo oficial do time Nunes Sports', 79.99);
INSERT INTO tb_product (name, description, price) VALUES ('Rede de Futebol', 'Rede resistente para treinos e partidas', 49.90);
INSERT INTO tb_product (name, description, price) VALUES ('Tênis de Corrida Asics Gel', 'Tênis de alta performance para corridas', 189.99);
INSERT INTO tb_product (name, description, price) VALUES ('Shorts Térmico para Corrida', 'Shorts confortável para corridas longas', 59.90);
INSERT INTO tb_product (name, description, price) VALUES ('Garrafa de Hidratação Esportiva', 'Garrafa com design ergonômico para atletas', 39.90);
INSERT INTO tb_product (name, description, price) VALUES ('Bola de Basquete Spalding', 'Bola oficial de basquete para treinos e competições', 79.90);
INSERT INTO tb_product (name, description, price) VALUES ('Tênis de Basquete Adidas', 'Tênis de alta aderência e suporte para jogadores de basquete', 119.99);
INSERT INTO tb_product (name, description, price) VALUES ('Aro de Basquete Resistente', 'Aro de aço para prática intensa de basquete', 79.90);
INSERT INTO tb_product (name, description, price) VALUES ('Luvas de Goleiro Profissional', 'Luvas com grip superior para goleiros', 149.90);
INSERT INTO tb_product (name, description, price) VALUES ('Caneleira de Proteção Nike', 'Caneleira leve e resistente para proteção durante os jogos', 69.90);
INSERT INTO tb_product (name, description, price) VALUES ('Meião Esportivo', 'Meião confortável para prática esportiva', 19.90);
INSERT INTO tb_product (name, description, price) VALUES ('Raquete de Tênis Wilson', 'Raquete de alta qualidade para jogadores exigentes', 159.90);
INSERT INTO tb_product (name, description, price) VALUES ('Bola de Vôlei Mikasa', 'Bola oficial para treinos e competições de vôlei', 89.90);
INSERT INTO tb_product (name, description, price) VALUES ('Tênis de Squash Head', 'Calçado projetado para movimentos rápidos em quadra', 129.90);
INSERT INTO tb_product (name, description, price) VALUES ('Mochila Esportiva Adidas', 'Mochila resistente e espaçosa para atletas', 79.90);
INSERT INTO tb_product (name, description, price) VALUES ('Boné de Corrida', 'Boné leve e respirável para corridas ao ar livre', 29.90);
INSERT INTO tb_product (name, description, price) VALUES ('Corda de Pular Profissional', 'Corda ajustável para treinos intensos de cardio', 14.90);
INSERT INTO tb_product (name, description, price) VALUES ('Joelheira de Suporte', 'Joelheira confortável para suporte durante atividades físicas', 34.90);
INSERT INTO tb_product (name, description, price) VALUES ('Skate Completo', 'Skate para iniciantes com design moderno', 99.90);
INSERT INTO tb_product (name, description, price) VALUES ('Relógio Esportivo Garmin', 'Relógio com recursos avançados para monitoramento de atividades', 279.90);
INSERT INTO tb_product (name, description, price) VALUES ('Máscara de Treino', 'Máscara para simular treinamento em altas altitudes', 44.90);
INSERT INTO tb_product (name, description, price) VALUES ('Elásticos de Resistência', 'Conjunto de elásticos para treinos de resistência', 29.90);
INSERT INTO tb_product (name, description, price) VALUES ('Squeeze de Alumínio', 'Squeeze durável para manter-se hidratado durante os exercícios', 19.90);
create table tb_product (price float(53) not null, id bigserial not null, description TEXT, name varchar(255), primary key (id));
INSERT INTO tb_product (name, description, price) VALUES ('Bola de Futebol', 'Bola de Futebol Nunes Sports: durável, design clássico, toques precisos', 119.90);
INSERT INTO tb_product (name, description, price) VALUES ('Chuteira Nike Mercurial', 'Chuteira profissional para jogadores de futebol', 229.90);
INSERT INTO tb_product (name, description, price) VALUES ('Camisa Oficial do Time', 'Camisa de jogo oficial do time Nunes Sports', 79.99);
INSERT INTO tb_product (name, description, price) VALUES ('Rede de Futebol', 'Rede resistente para treinos e partidas', 49.90);
INSERT INTO tb_product (name, description, price) VALUES ('Tênis de Corrida Asics Gel', 'Tênis de alta performance para corridas', 189.99);
INSERT INTO tb_product (name, description, price) VALUES ('Shorts Térmico para Corrida', 'Shorts confortável para corridas longas', 59.90);
INSERT INTO tb_product (name, description, price) VALUES ('Garrafa de Hidratação Esportiva', 'Garrafa com design ergonômico para atletas', 39.90);
INSERT INTO tb_product (name, description, price) VALUES ('Bola de Basquete Spalding', 'Bola oficial de basquete para treinos e competições', 79.90);
INSERT INTO tb_product (name, description, price) VALUES ('Tênis de Basquete Adidas', 'Tênis de alta aderência e suporte para jogadores de basquete', 119.99);
INSERT INTO tb_product (name, description, price) VALUES ('Aro de Basquete Resistente', 'Aro de aço para prática intensa de basquete', 79.90);
INSERT INTO tb_product (name, description, price) VALUES ('Luvas de Goleiro Profissional', 'Luvas com grip superior para goleiros', 149.90);
INSERT INTO tb_product (name, description, price) VALUES ('Caneleira de Proteção Nike', 'Caneleira leve e resistente para proteção durante os jogos', 69.90);
INSERT INTO tb_product (name, description, price) VALUES ('Meião Esportivo', 'Meião confortável para prática esportiva', 19.90);
INSERT INTO tb_product (name, description, price) VALUES ('Raquete de Tênis Wilson', 'Raquete de alta qualidade para jogadores exigentes', 159.90);
INSERT INTO tb_product (name, description, price) VALUES ('Bola de Vôlei Mikasa', 'Bola oficial para treinos e competições de vôlei', 89.90);
INSERT INTO tb_product (name, description, price) VALUES ('Tênis de Squash Head', 'Calçado projetado para movimentos rápidos em quadra', 129.90);
INSERT INTO tb_product (name, description, price) VALUES ('Mochila Esportiva Adidas', 'Mochila resistente e espaçosa para atletas', 79.90);
INSERT INTO tb_product (name, description, price) VALUES ('Boné de Corrida', 'Boné leve e respirável para corridas ao ar livre', 29.90);
INSERT INTO tb_product (name, description, price) VALUES ('Corda de Pular Profissional', 'Corda ajustável para treinos intensos de cardio', 14.90);
INSERT INTO tb_product (name, description, price) VALUES ('Joelheira de Suporte', 'Joelheira confortável para suporte durante atividades físicas', 34.90);
INSERT INTO tb_product (name, description, price) VALUES ('Skate Completo', 'Skate para iniciantes com design moderno', 99.90);
INSERT INTO tb_product (name, description, price) VALUES ('Relógio Esportivo Garmin', 'Relógio com recursos avançados para monitoramento de atividades', 279.90);
INSERT INTO tb_product (name, description, price) VALUES ('Máscara de Treino', 'Máscara para simular treinamento em altas altitudes', 44.90);
INSERT INTO tb_product (name, description, price) VALUES ('Elásticos de Resistência', 'Conjunto de elásticos para treinos de resistência', 29.90);
INSERT INTO tb_product (name, description, price) VALUES ('Squeeze de Alumínio', 'Squeeze durável para manter-se hidratado durante os exercícios', 19.90);
