INSERT INTO tb_product (name, description, price) VALUES ('Bola de Futebol', 'Bola de Futebol Nunes Sports: durável, design clássico, toques precisos', 120.00);
INSERT INTO tb_product (name, description, price) VALUES ('Chuteira Nike Mercurial', 'Chuteira profissional para jogadores de futebol', 230.00);
INSERT INTO tb_product (name, description, price) VALUES ('Camisa Oficial do Time', 'Camisa de jogo oficial do time Nunes Sports', 80.00);
INSERT INTO tb_product (name, description, price) VALUES ('Rede de Futebol', 'Rede resistente para treinos e partidas', 50.00);
INSERT INTO tb_product (name, description, price) VALUES ('Tênis de Corrida Asics Gel', 'Tênis de alta performance para corridas', 180.00);
INSERT INTO tb_product (name, description, price) VALUES ('Shorts Térmico para Corrida', 'Shorts confortável para corridas longas', 45.00);
INSERT INTO tb_product (name, description, price) VALUES ('Garrafa de Hidratação Esportiva', 'Garrafa com design ergonômico para atletas', 15.00);
INSERT INTO tb_product (name, description, price) VALUES ('Bola de Basquete Spalding', 'Bola oficial de basquete para treinos e competições', 60.00);
INSERT INTO tb_product (name, description, price) VALUES ('Tênis de Basquete Adidas', 'Tênis de alta aderência e suporte para jogadores de basquete', 120.00);
INSERT INTO tb_product (name, description, price) VALUES ('Aro de Basquete Resistente', 'Aro de aço para prática intensa de basquete', 80.00);